package com.yz.base.user.pojo;
// Generated 2016-5-7 14:29:39 by Hibernate Tools 4.3.1.Final

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * VUserRoleResources generated by hbm2java
 */
@Entity
@Table(name = "v_user_role_resources")
public class VUserRoleResources implements java.io.Serializable {


	private String id;
	private String userAccount;
	private String roleCode;
	private String roleName;
	private String userCode;
	private String userName;
	private String resourceCode;
	private String resourceName;
	private Integer resourceType;
	private String resourceUrl;
	private String parentResCode;
	private String resourceDesc;
	private Integer orderd;

	public VUserRoleResources() {
	}

	public VUserRoleResources(String id, String userAccount, String roleCode, String roleName, String userCode,
			String userName, String resourceCode, String resourceName, Integer resourceType, String resourceUrl,
			String parentResCode, String resourceDesc, Integer orderd) {
		this.id = id;
		this.userAccount = userAccount;
		this.roleCode = roleCode;
		this.roleName = roleName;
		this.userCode = userCode;
		this.userName = userName;
		this.resourceCode = resourceCode;
		this.resourceName = resourceName;
		this.resourceType = resourceType;
		this.resourceUrl = resourceUrl;
		this.parentResCode = parentResCode;
		this.resourceDesc = resourceDesc;
		this.orderd = orderd;
	}

	@Id
	@GeneratedValue
	@Column(name = "ID", length = 36)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "USER_ACCOUNT", length = 32)
	public String getUserAccount() {
		return this.userAccount;
	}

	public void setUserAccount(String userAccount) {
		this.userAccount = userAccount;
	}

	@Column(name = "ROLE_CODE", length = 32)
	public String getRoleCode() {
		return this.roleCode;
	}

	public void setRoleCode(String roleCode) {
		this.roleCode = roleCode;
	}

	@Column(name = "ROLE_NAME", length = 50)
	public String getRoleName() {
		return this.roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	@Column(name = "USER_CODE", length = 32)
	public String getUserCode() {
		return this.userCode;
	}

	public void setUserCode(String userCode) {
		this.userCode = userCode;
	}

	@Column(name = "USER_NAME")
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "RESOURCE_CODE", length = 32)
	public String getResourceCode() {
		return this.resourceCode;
	}

	public void setResourceCode(String resourceCode) {
		this.resourceCode = resourceCode;
	}

	@Column(name = "RESOURCE_NAME")
	public String getResourceName() {
		return this.resourceName;
	}

	public void setResourceName(String resourceName) {
		this.resourceName = resourceName;
	}

	@Column(name = "RESOURCE_TYPE")
	public Integer getResourceType() {
		return this.resourceType;
	}

	public void setResourceType(Integer resourceType) {
		this.resourceType = resourceType;
	}

	@Column(name = "RESOURCE_URL")
	public String getResourceUrl() {
		return this.resourceUrl;
	}

	public void setResourceUrl(String resourceUrl) {
		this.resourceUrl = resourceUrl;
	}

	@Column(name = "PARENT_RES_CODE", length = 32)
	public String getParentResCode() {
		return this.parentResCode;
	}

	public void setParentResCode(String parentResCode) {
		this.parentResCode = parentResCode;
	}

	@Column(name = "RESOURCE_DESC")
	public String getResourceDesc() {
		return this.resourceDesc;
	}

	public void setResourceDesc(String resourceDesc) {
		this.resourceDesc = resourceDesc;
	}

	@Column(name = "ORDERD")
	public Integer getOrderd() {
		return this.orderd;
	}

	public void setOrderd(Integer orderd) {
		this.orderd = orderd;
	}

}
