package com.yz.base.resource.pojo;
// Generated 2016-5-7 15:00:25 by Hibernate Tools 4.3.1.Final

import java.sql.Timestamp;
import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import javax.persistence.Version;

/**
 * BaseResource generated by hbm2java
 */
@Entity
@Table(name = "base_resource")
public class BaseResource implements java.io.Serializable {

	private Integer id;
	private Integer version;
	private String resourceName;
	private Integer resourceType;
	private String resourceUrl;
	private String icon;
	private String code;
	private String resourceDesc;
	private String parentResCode;
	private Integer status;
	private String createdBy;
	private Timestamp createdDate;
	private String lastUpdatedBy;
	private Timestamp lastUpdatedDate;
	private Integer orderd;
	private List<BaseResource> baseResourceList;
	public BaseResource() {
	}

	public BaseResource(String resourceName, Integer resourceType, String resourceUrl, String code,String icon, String resourceDesc,
			String parentResCode, Integer status, String createdBy, Timestamp createdDate, String lastUpdatedBy,
			Timestamp lastUpdatedDate, Integer orderd) {
		this.resourceName = resourceName;
		this.resourceType = resourceType;
		this.resourceUrl = resourceUrl;
		this.code = code;
		this.resourceDesc = resourceDesc;
		this.parentResCode = parentResCode;
		this.status = status;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.lastUpdatedBy = lastUpdatedBy;
		this.lastUpdatedDate = lastUpdatedDate;
		this.orderd = orderd;
		this.icon=icon;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Version
	@Column(name = "VERSION")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@Column(name = "RESOURCE_NAME")
	public String getResourceName() {
		return this.resourceName;
	}

	public void setResourceName(String resourceName) {
		this.resourceName = resourceName;
	}

	@Column(name = "RESOURCE_TYPE")
	public Integer getResourceType() {
		return this.resourceType;
	}

	public void setResourceType(Integer resourceType) {
		this.resourceType = resourceType;
	}

	@Column(name = "RESOURCE_URL")
	public String getResourceUrl() {
		return this.resourceUrl;
	}

	public void setResourceUrl(String resourceUrl) {
		this.resourceUrl = resourceUrl;
	}

	/**
	 * @return the icon
	 */
	@Column(name = "ICON", length = 255)
	public String getIcon() {
		return icon;
	}

	/**
	 * @param icon the icon to set
	 */
	public void setIcon(String icon) {
		this.icon = icon;
	}

	@Column(name = "CODE", length = 32)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "RESOURCE_DESC")
	public String getResourceDesc() {
		return this.resourceDesc;
	}

	public void setResourceDesc(String resourceDesc) {
		this.resourceDesc = resourceDesc;
	}

	@Column(name = "PARENT_RES_CODE", length = 32)
	public String getParentResCode() {
		return this.parentResCode;
	}

	public void setParentResCode(String parentResCode) {
		this.parentResCode = parentResCode;
	}

	@Column(name = "STATUS")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@Column(name = "CREATED_BY", length = 32)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_DATE", length = 19)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Timestamp createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "LAST_UPDATED_BY", length = 32)
	public String getLastUpdatedBy() {
		return this.lastUpdatedBy;
	}

	public void setLastUpdatedBy(String lastUpdatedBy) {
		this.lastUpdatedBy = lastUpdatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LAST_UPDATED_DATE", length = 19)
	public Date getLastUpdatedDate() {
		return this.lastUpdatedDate;
	}

	public void setLastUpdatedDate(Timestamp lastUpdatedDate) {
		this.lastUpdatedDate = lastUpdatedDate;
	}

	@Column(name = "ORDERD")
	public Integer getOrderd() {
		return this.orderd;
	}

	public void setOrderd(Integer orderd) {
		this.orderd = orderd;
	}

	/**
	 * @return the baseResourceList
	 */
	@Transient
	public List<BaseResource> getBaseResourceList() {
		return baseResourceList;
	}

	/**
	 * @param baseResourceList the baseResourceList to set
	 */
	public void setBaseResourceList(List<BaseResource> baseResourceList) {
		this.baseResourceList = baseResourceList;
	}

}
